version: '3.5'
services:
  yarn:
    container_name: we-plant-admin
    restart: always
    build:
      context: yarn
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
      - "3001:3001"
  node:
    container_name: we-plant-app
    restart: always
    build: 
      context: node
      dockerfile: Dockerfile.dev
    ports:
      - "8100:8100"
  maven:
    depends_on:
      - db
    container_name: we-plant-api
    restart: always
    build:
      context: maven
      dockerfile: Dockerfile.dev
    ports:
        - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/weplant
      - SPRING_DATASOURCE_USERNAME=we-plant
      - SPRING_DATASOURCE_PASSWORD=password
      
  db:
    build:
      context: postgres
      dockerfile: Dockerfile.dev
    container_name: postgres
    user: postgres
    ports:
      - "5432:5432"
    
