FROM node:11.15.0-stretch
SHELL ["/bin/bash", "--login", "-c"]
RUN apt update
RUN apt install git -y
RUN apt install curl -y
RUN . ~/.bashrc
RUN git clone https://github.com/Pavaz97/we-plant-app.git
COPY we-plant-app .
WORKDIR /we-plant-app
RUN git pull
RUN npm install
CMD [ "npm","run", "start" ]
EXPOSE 8100