FROM postgres:14
ENV POSTGRES_PASSWORD password
COPY start.sql docker-entrypoint-initdb.d/
COPY z_dump-weplant-202211272109.sql docker-entrypoint-initdb.d/
# COPY z.sh docker-entrypoint-initdb.d/
# RUN chmod 0755 /docker-entrypoint-initdb.d/z.sh
# RUN psql -d postgres -a -f start.sql
